Update to new standard
architect-templates/asp-net-core pull request #3
Opened 2023-03-16 22:01 UTC by mueschm

## Overview
Update to the new standard. This project mostly already conformed, so just updated some of the styling and the readme.

## Changes
1. Remove the big block of text on the site
2. Show movie form by default
3. Updated readme

## Pictures
### Local

<img width="1228" alt="chrome_EyyWtiUDpN" src="https://user-images.githubusercontent.com/532523/225761974-ff481a9e-6e92-4e64-99c8-46a3dfbb3224.png">

### Dev

<img width="1230" alt="chrome_6kGIaaWlnu" src="https://user-images.githubusercontent.com/532523/225762050-a6beff2f-bf5c-4be7-a9bf-3c0585042369.png">

2023-03-21 14:32 UTC, ryan-cahill requested changes
Why is there an item seeded in the DB when the app starts? I think that could be confusing to some users

2023-03-21 14:32 UTC, ryan-cahill commented on README.md
> +# Go Starter Project
I hadn't realized that C# code looked so much like Go code

2023-03-21 14:32 UTC, ryan-cahill commented on README.md
> +Give it a try! Search inside your project for “Favorite Movie” and change this string to "Favorite Pizza" Once you save
The "Favorite movie" header mentioned here isn't included in the template

2023-03-21 14:43 UTC, ryan-cahill commented
Also in testing the app (noticed with running `architect dev --debug=false` if you submit the form, then refresh the page after, it keeps submitting the form over and over on page refresh even though there's also nothing in the text fields

2023-03-21 22:17 UTC, mueschm commented
Updated
![image](https://user-images.githubusercontent.com/532523/226754479-d87862c3-0b8b-4b91-b44a-636fd832d843.png)

2023-03-22 13:47 UTC, ryan-cahill commented
Thanks for fixing those things. Two things left:

1. We added a DB liveness probe to the other templates which should be added here too
```
    liveness_probe:
      command: pg_isready -d ${{ secrets.database_name }} -U ${{ secrets.postgres_username }}
      interval: 10s
      failure_threshold: 3
```
2. I still think it's weird that there's an item seeded in the database when the app starts. It's even weirder that the rating is 10 when it's only supposed to be 1-5 according to the text field's placeholder

2023-03-22 13:48 UTC, ryan-cahill requested changes
Thanks for fixing those things. Two things left:

1. We added a DB liveness probe to the other templates which should be added here too
```
    liveness_probe:
      command: pg_isready -d ${{ secrets.database_name }} -U ${{ secrets.postgres_username }}
      interval: 10s
      failure_threshold: 3
```
2. I still think it's weird that there's an item seeded in the database when the app starts. It's even weirder that the rating is 10 when it's only supposed to be 1-5 according to the text field's placeholder

2023-03-22 15:46 UTC, mueschm commented
1. Liveness probe is in. Added to others but forget here so good catch.
2. Removed the item so it does not show up.
3. You are seeing that because ASP.net by default requires a valid SSL cert to run. You can disable that but as our default behavior is to add SSL certs to everything it made no sense. I assume you deployed to staging or local since my production deploy works fine.

2023-03-22 19:33 UTC, ryan-cahill approved these changes
`architect dev`
![image](https://user-images.githubusercontent.com/8558567/227015089-bffc8989-253e-45f6-9a5f-961c87679ac5.png)

`architect dev --debug=false`
![image](https://user-images.githubusercontent.com/8558567/227015568-a6b5f144-b2a9-4916-ab06-de7fb2420e41.png)

`architect deploy asp-net-core -e example-environment --auto-approve`
![image](https://user-images.githubusercontent.com/8558567/227016658-6550c35a-f270-4125-8364-91fb793830e6.png)

2023-03-22 20:24 UTC, Zach-at-Arch approved these changes
Looks good from my end! Everything runs smoothly and works as expected

2023-03-22 20:26 UTC, merged